---
description: Tracks Duo Workflow resumes
internal_events: true
action: resume_duo_workflow
product_group: duo_workflow
additional_properties:
  label:
    description: Hardcoded string workflow_resume_event
  property:
    description: resume_request_by_<user|duo_workflow>_<after_input|after_approval (optional)>
  value:
    description: Workflow Id that can be used to connect this event to others that happen when the workflow is completed.
milestone: '17.10'
introduced_by_url: https://gitlab.com/gitlab-org/duo-workflow/duo-workflow-service/-/merge_requests/279
distributions:
  - ee
tiers:
  - ultimate