# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contract import contract_pb2 as contract_dot_contract__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contract/contract_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DuoWorkflowStub(object):
    """DuoWorkflow is the gRPC service that orchestrates AI-powered workflow execution
    for GitLab Duo. It serves all GitLab deployment types (SaaS, self-managed, dedicated,
    self-hosted) and provides RPCs for running workflows, managing authentication,
    discovering available tools and flows, and self-hosted billing tracking.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWorkflow = channel.stream_stream(
                '/DuoWorkflow/ExecuteWorkflow',
                request_serializer=contract_dot_contract__pb2.ClientEvent.SerializeToString,
                response_deserializer=contract_dot_contract__pb2.Action.FromString,
                _registered_method=True)
        self.GenerateToken = channel.unary_unary(
                '/DuoWorkflow/GenerateToken',
                request_serializer=contract_dot_contract__pb2.GenerateTokenRequest.SerializeToString,
                response_deserializer=contract_dot_contract__pb2.GenerateTokenResponse.FromString,
                _registered_method=True)
        self.ListCapabilities = channel.unary_unary(
                '/DuoWorkflow/ListCapabilities',
                request_serializer=contract_dot_contract__pb2.ListCapabilitiesRequest.SerializeToString,
                response_deserializer=contract_dot_contract__pb2.ListCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/DuoWorkflow/ListTools',
                request_serializer=contract_dot_contract__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=contract_dot_contract__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ListFlows = channel.unary_unary(
                '/DuoWorkflow/ListFlows',
                request_serializer=contract_dot_contract__pb2.ListFlowsRequest.SerializeToString,
                response_deserializer=contract_dot_contract__pb2.ListFlowsResponse.FromString,
                _registered_method=True)
        self.TrackSelfHostedExecuteWorkflow = channel.stream_stream(
                '/DuoWorkflow/TrackSelfHostedExecuteWorkflow',
                request_serializer=contract_dot_contract__pb2.TrackSelfHostedClientEvent.SerializeToString,
                response_deserializer=contract_dot_contract__pb2.TrackSelfHostedAction.FromString,
                _registered_method=True)
        self.ValidateFlowConfig = channel.unary_unary(
                '/DuoWorkflow/ValidateFlowConfig',
                request_serializer=contract_dot_contract__pb2.ValidateFlowConfigRequest.SerializeToString,
                response_deserializer=contract_dot_contract__pb2.ValidateFlowConfigResponse.FromString,
                _registered_method=True)


class DuoWorkflowServicer(object):
    """DuoWorkflow is the gRPC service that orchestrates AI-powered workflow execution
    for GitLab Duo. It serves all GitLab deployment types (SaaS, self-managed, dedicated,
    self-hosted) and provides RPCs for running workflows, managing authentication,
    discovering available tools and flows, and self-hosted billing tracking.
    """

    def ExecuteWorkflow(self, request_iterator, context):
        """ExecuteWorkflow starts a bidirectional streaming session for running a Duo Workflow.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateToken(self, request, context):
        """GenerateToken issues a short-lived authentication token for a workflow session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCapabilities(self, request, context):
        """ListCapabilities returns the capabilities advertised by the server for capability negotiation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """ListTools returns the set of tools available to the workflow executor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlows(self, request, context):
        """ListFlows returns the set of flow configurations available for execution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackSelfHostedExecuteWorkflow(self, request_iterator, context):
        """TrackSelfHostedExecuteWorkflow is the billing bridge for self-hosted Duo deployments using
        cloud (online) licensing. Workhorse opens this bidirectional stream to Cloud DWS for the
        lifetime of a workflow. Cloud DWS performs an upfront quota check on stream open. For each
        LLM call, the self-hosted DWS sends a TrackSelfHostedClientEvent; Cloud DWS responds with a
        TrackSelfHostedAction to allow or deny the call. LLM traffic never leaves customer infrastructure.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateFlowConfig(self, request, context):
        """ValidateFlowConfig validates a provided flow configuration against the registered schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DuoWorkflowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteWorkflow': grpc.stream_stream_rpc_method_handler(
                    servicer.ExecuteWorkflow,
                    request_deserializer=contract_dot_contract__pb2.ClientEvent.FromString,
                    response_serializer=contract_dot_contract__pb2.Action.SerializeToString,
            ),
            'GenerateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateToken,
                    request_deserializer=contract_dot_contract__pb2.GenerateTokenRequest.FromString,
                    response_serializer=contract_dot_contract__pb2.GenerateTokenResponse.SerializeToString,
            ),
            'ListCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapabilities,
                    request_deserializer=contract_dot_contract__pb2.ListCapabilitiesRequest.FromString,
                    response_serializer=contract_dot_contract__pb2.ListCapabilitiesResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=contract_dot_contract__pb2.ListToolsRequest.FromString,
                    response_serializer=contract_dot_contract__pb2.ListToolsResponse.SerializeToString,
            ),
            'ListFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFlows,
                    request_deserializer=contract_dot_contract__pb2.ListFlowsRequest.FromString,
                    response_serializer=contract_dot_contract__pb2.ListFlowsResponse.SerializeToString,
            ),
            'TrackSelfHostedExecuteWorkflow': grpc.stream_stream_rpc_method_handler(
                    servicer.TrackSelfHostedExecuteWorkflow,
                    request_deserializer=contract_dot_contract__pb2.TrackSelfHostedClientEvent.FromString,
                    response_serializer=contract_dot_contract__pb2.TrackSelfHostedAction.SerializeToString,
            ),
            'ValidateFlowConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateFlowConfig,
                    request_deserializer=contract_dot_contract__pb2.ValidateFlowConfigRequest.FromString,
                    response_serializer=contract_dot_contract__pb2.ValidateFlowConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DuoWorkflow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DuoWorkflow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DuoWorkflow(object):
    """DuoWorkflow is the gRPC service that orchestrates AI-powered workflow execution
    for GitLab Duo. It serves all GitLab deployment types (SaaS, self-managed, dedicated,
    self-hosted) and provides RPCs for running workflows, managing authentication,
    discovering available tools and flows, and self-hosted billing tracking.
    """

    @staticmethod
    def ExecuteWorkflow(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/DuoWorkflow/ExecuteWorkflow',
            contract_dot_contract__pb2.ClientEvent.SerializeToString,
            contract_dot_contract__pb2.Action.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DuoWorkflow/GenerateToken',
            contract_dot_contract__pb2.GenerateTokenRequest.SerializeToString,
            contract_dot_contract__pb2.GenerateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DuoWorkflow/ListCapabilities',
            contract_dot_contract__pb2.ListCapabilitiesRequest.SerializeToString,
            contract_dot_contract__pb2.ListCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DuoWorkflow/ListTools',
            contract_dot_contract__pb2.ListToolsRequest.SerializeToString,
            contract_dot_contract__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DuoWorkflow/ListFlows',
            contract_dot_contract__pb2.ListFlowsRequest.SerializeToString,
            contract_dot_contract__pb2.ListFlowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackSelfHostedExecuteWorkflow(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/DuoWorkflow/TrackSelfHostedExecuteWorkflow',
            contract_dot_contract__pb2.TrackSelfHostedClientEvent.SerializeToString,
            contract_dot_contract__pb2.TrackSelfHostedAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateFlowConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DuoWorkflow/ValidateFlowConfig',
            contract_dot_contract__pb2.ValidateFlowConfigRequest.SerializeToString,
            contract_dot_contract__pb2.ValidateFlowConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
