apiVersion: runway/v1
kind: RunwayKubernetesDeployment

ai-gateway-eks:
  metadata:
    labels:
      gitlab.com/department: eng-dev
      gitlab.com/department_group: eng-dev-create-shared-infra
      gitlab.com/product_category: code_creation
      gitlab.com/owner_email_handle: mnohr

  serviceMixins:
    - "runway-eks.service-mixin"

  spec:
    environment:
      AIGW_ENVIRONMENT: "production"
      AIGW_GITLAB_URL: "https://gitlab.com"
      AIGW_GITLAB_API_URL: "https://gitlab.com/api/v4/"
      AIGW_CUSTOMER_PORTAL_URL: "https://customers.gitlab.com"
      AIGW_GLGO_BASE_URL: "https://auth.aws.gitlab.com"
      AIGW_GOOGLE_CLOUD_PLATFORM__PROJECT: "gitlab-ai-framework-leg-prod"
      AIGW_VERTEX_SEARCH__FALLBACK_DATASTORE_VERSION: "17.0"
      AIGW_SNOWPLOW__ENABLED: "true"
      AIGW_SNOWPLOW__ENDPOINT: "https://snowplowprd.trx.gitlab.net"
      AIGW_SNOWPLOW__BATCH_SIZE: "1"
      AIGW_SNOWPLOW__THREAD_COUNT: "1"
      AIGW_INTERNAL_EVENT__ENABLED: "true"
      AIGW_INTERNAL_EVENT__ENDPOINT: "https://snowplowprd.trx.gitlab.net"
      AIGW_INTERNAL_EVENT__BATCH_SIZE: "1"
      AIGW_INTERNAL_EVENT__THREAD_COUNT: "1"
      AIGW_BILLING_EVENT__ENABLED: "true"
      AIGW_BILLING_EVENT__ENDPOINT: "https://billing.prdsub.gitlab.net"
      AIGW_BILLING_EVENT__NAMESPACE: "gl"
      AIGW_BILLING_EVENT__BATCH_SIZE: "1"
      AIGW_BILLING_EVENT__THREAD_COUNT: "1"
      AIGW_FEATURE_FLAGS__DISALLOWED_FLAGS: '{"self-managed": ["expanded_ai_logging"]}'
      AIGW_MODEL_ENDPOINTS__FIREWORKS_REGIONAL_ENDPOINTS: '{ "us": { "qwen2p5-coder-7b": { "endpoint": "https://gitlab-84f6d9f4.tokyo.direct.fireworks.ai/v1", "identifier": "accounts/fireworks/models/qwen2p5-coder-7b#accounts/gitlab/deployments/84f6d9f4" }, "codestral-2501": { "endpoint": "https://gitlab-a8a5a0a6.us-virginia-1.direct.fireworks.ai/v1", "identifier": "accounts/gitlab/models/codestral-2501" }, "codestral-2508": { "endpoint": "https://gitlab-hwxx5e87.us-illinois-1.direct.fireworks.ai/v1", "identifier": "accounts/gitlab/models/codestral-2508" } }, "europe": { "qwen2p5-coder-7b": { "endpoint": "https://gitlab-84f6d9f4.tokyo.direct.fireworks.ai/v1", "identifier": "accounts/fireworks/models/qwen2p5-coder-7b#accounts/gitlab/deployments/84f6d9f4" }, "codestral-2501": { "endpoint": "https://gitlab-6fd60574.eu-frankfurt-1.direct.fireworks.ai/v1", "identifier": "accounts/gitlab/models/codestral-2501" }, "codestral-2508": { "endpoint": "https://gitlab-xj9wqif6.eu-frankfurt-1.direct.fireworks.ai/v1", "identifier": "accounts/gitlab/models/codestral-2508" } }, "asia": { "qwen2p5-coder-7b": { "endpoint": "https://gitlab-84f6d9f4.tokyo.direct.fireworks.ai/v1", "identifier": "accounts/fireworks/models/qwen2p5-coder-7b#accounts/gitlab/deployments/84f6d9f4" }, "codestral-2501": { "endpoint": "https://gitlab-3065d573.tokyo.direct.fireworks.ai/v1", "identifier": "accounts/gitlab/models/codestral-2501" } }}'
      AIGW_FEATURE_FLAGS__FIREWORKS_SCORE_THRESHOLD: '{"qwen2p5-coder-7b": -1.5}'
      GOOGLE_APPLICATION_CREDENTIALS: '/secrets/gcp-service-account/credentials.json'

  workloadSecrets:
    - name: env-vars
    - name: gcp-service-account-legacy

  secretEnvFrom:
    - env-vars

  secretVolumes:
    - name: gcp-service-account-legacy
      path: /secrets/gcp-service-account
