apiVersion: runway/v1
kind: RunwayKubernetesDeployment

ai-gateway-eks:
  metadata:
    labels:
      gitlab.com/department: eng-dev
      gitlab.com/department_group: eng-dev-create-shared-infra
      gitlab.com/product_category: code_creation
      gitlab.com/owner_email_handle: mnohr

  serviceMixins:
    - "runway-eks.service-mixin"
