apiVersion: runway/v1
kind: RunwayKubernetesDeployment

ai-gateway-eks:
  metadata:
    labels:
      gitlab.com/department: eng-dev
      gitlab.com/department_group: eng-dev-create-shared-infra
      gitlab.com/product_category: code_creation
      gitlab.com/owner_email_handle: mnohr

  serviceMixins:
    - "runway-eks.service-mixin"

  spec:
    environment:
      AIGW_ENVIRONMENT: "production"
      AIGW_GITLAB_URL: "https://gitlab.com"
      AIGW_GITLAB_API_URL: "https://gitlab.com/api/v4/"
      AIGW_CUSTOMER_PORTAL_URL: "https://customers.gitlab.com"
      AIGW_GLGO_BASE_URL: "https://auth.aws.gitlab.com"
      AIGW_GOOGLE_CLOUD_PLATFORM__PROJECT: "gitlab-ai-framework-leg-prod"
      AIGW_VERTEX_SEARCH__FALLBACK_DATASTORE_VERSION: "18.9"
      AIGW_SNOWPLOW__ENABLED: "true"
      AIGW_SNOWPLOW__ENDPOINT: "https://snowplowprd.trx.gitlab.net"
      AIGW_SNOWPLOW__BATCH_SIZE: "1"
      AIGW_SNOWPLOW__THREAD_COUNT: "1"
      AIGW_INTERNAL_EVENT__ENABLED: "true"
      AIGW_INTERNAL_EVENT__ENDPOINT: "https://snowplowprd.trx.gitlab.net"
      AIGW_INTERNAL_EVENT__BATCH_SIZE: "1"
      AIGW_INTERNAL_EVENT__THREAD_COUNT: "5"
      AIGW_BILLING_EVENT__ENABLED: "true"
      AIGW_BILLING_EVENT__ENDPOINT: "https://billing.prdsub.gitlab.net"
      AIGW_BILLING_EVENT__NAMESPACE: "gl"
      AIGW_BILLING_EVENT__BATCH_SIZE: "1"
      AIGW_BILLING_EVENT__THREAD_COUNT: "5"
      AIGW_FEATURE_FLAGS__DISALLOWED_FLAGS: '{"self-managed": ["expanded_ai_logging"]}'
      AIGW_FEATURE_FLAGS__FIREWORKS_SCORE_THRESHOLD: '{"qwen2p5-coder-7b": -1.5}'
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/gcp-service-account/credentials.json"

  workloadSecrets:
    - name: env-vars
    - name: gcp-service-account-legacy

  secretEnvFrom:
    - env-vars

  secretVolumes:
    - name: gcp-service-account-legacy
      path: /secrets/gcp-service-account
