apiVersion: runway/v1
kind: RunwayKubernetesDeployment

ai-gateway-eks:
  metadata:
    labels:
      gitlab.com/department: eng-dev
      gitlab.com/department_group: eng-dev-create-shared-infra
      gitlab.com/product_category: code_creation
      gitlab.com/owner_email_handle: mnohr

  serviceMixins:
    - "runway-eks.service-mixin"

  spec:
    services:
      app:
        environment:
          AIGW_ENVIRONMENT: "staging"
          AIGW_GITLAB_URL: "https://staging.gitlab.com"
          AIGW_GITLAB_API_URL: "https://staging.gitlab.com/api/v4/"
          AIGW_CUSTOMER_PORTAL_URL: "https://customers.staging.gitlab.com"
          AIGW_GLGO_BASE_URL: "https://app.glgo-eks.${region}.aws.runway.gitlab.net"
          AIGW_GOOGLE_CLOUD_PLATFORM__PROJECT: "gitlab-ai-framework-stage"
          AIGW_VERTEX_SEARCH__FALLBACK_DATASTORE_VERSION: "17.0"
          AIGW_SNOWPLOW__ENABLED: "false"
          AIGW_INTERNAL_EVENT__ENABLED: "false"
          AIGW_BILLING_EVENT__ENABLED: "false"
          AIGW_MODEL_ENDPOINTS__FIREWORKS_REGIONAL_ENDPOINTS: '{ "us": {"qwen2p5-coder-7b": { "endpoint": "https://gitlab-ac589058.us-virginia-1.direct.fireworks.ai/v1", "identifier": "accounts/fireworks/models/qwen2p5-coder-7b#accounts/gitlab/deployments/ac589058"}, "codestral-2501": {"endpoint": "https://gitlab-fd046d6c.us-arizona-1.direct.fireworks.ai/v1","identifier": "accounts/gitlab/models/codestral-2501"}}}'
          AIGW_FEATURE_FLAGS__FIREWORKS_SCORE_THRESHOLD: '{"qwen2p5-coder-7b": -1.5}'
