inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Include
    - Exclude
    - AllowedPatterns

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - lib/proto/*_pb.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Enabled: false
