---
description: Tracks code generation requests served through the Amazon Q integration
internal_events: true
action: request_amazon_q_integration_generate_code
product_group: duo_chat
product_categories:
  - duo_chat
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/7024
tiers:
  - ultimate
