---
description: Tracks requests to the generate_cube_query unit primitive
internal_events: true
action: request_generate_cube_query
product_group: platform_insights
product_categories:
  - product_analytics_visualization
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - premium
  - ultimate
