---
description: Tracks requests to the measure_comment_temperature unit primitive
internal_events: true
action: request_measure_comment_temperature
product_group: ai_model_services
product_categories:
  - ai_abstraction_layer
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - premium
  - ultimate
