---
description: Tracks requests to the feature_discovery_search unit primitive
internal_events: true
action: request_feature_discovery_search
product_group: activation
product_categories:
  - activation
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - free
  - premium
  - ultimate
