---
description: Tracks requests to the observability_all unit primitive
internal_events: true
action: request_observability_all
product_group: platform_insights
product_categories:
  - observability
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - free
  - premium
  - ultimate
