---
description: Tracks requests to the ai_gateway_model_provider_proxy unit primitive
internal_events: true
action: request_ai_gateway_model_provider_proxy
product_group: agent_execution
product_categories:
  - duo_agent_platform
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - free
  - premium
  - ultimate
