---
description: Tracks requests to the security_scans unit primitive
internal_events: true
action: request_security_scans
product_group: code_scanning
product_categories:
  - static_application_security_testing
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - free
  - premium
  - ultimate
