---
description: Tracks requests to the duo_agent_platform unit primitive
internal_events: true
action: request_duo_agent_platform
product_group: agent_execution
product_categories:
  - duo_workflow
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - free
  - premium
  - ultimate
