---
description: Tracks requests to the generate_commit_message unit primitive
internal_events: true
action: request_generate_commit_message
product_group: code_review
product_categories:
  - code_review_workflow
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - premium
  - ultimate
