---
description: Tracks when document search API is called
internal_events: true
action: request_documentation_search
product_group: ai_framework
milestone: '17.3'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/1113
tiers:
  - free
  - premium
  - ultimate
