---
description: Tracks requests to the troubleshoot_job unit primitive
internal_events: true
action: request_troubleshoot_job
product_group: pipeline_execution
product_categories:
  - continuous_integration
milestone: '19.5'
introduced_by_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/merge_requests/6798
tiers:
  - premium
  - ultimate
