from duo_workflow_service.tools.work_items.queries.graphql_queries import (
    CREATE_NOTE_MUTATION,
    CREATE_WORK_ITEM_MUTATION,
    GET_GROUP_WORK_ITEM_NOTES_QUERY,
    GET_GROUP_WORK_ITEM_QUERY,
    GET_PROJECT_WORK_ITEM_NOTES_QUERY,
    GET_PROJECT_WORK_ITEM_QUERY,
    GET_WORK_ITEM_STATUSES_QUERY,
    GET_WORK_ITEM_TYPE_BY_NAME_QUERY,
    LIST_GROUP_WORK_ITEMS_QUERY,
    LIST_PROJECT_WORK_ITEMS_QUERY,
    UPDATE_WORK_ITEM_MUTATION,
)

__all__ = [
    "CREATE_NOTE_MUTATION",
    "CREATE_WORK_ITEM_MUTATION",
    "GET_GROUP_WORK_ITEM_NOTES_QUERY",
    "GET_GROUP_WORK_ITEM_QUERY",
    "GET_PROJECT_WORK_ITEM_NOTES_QUERY",
    "GET_PROJECT_WORK_ITEM_QUERY",
    "GET_WORK_ITEM_STATUSES_QUERY",
    "GET_WORK_ITEM_TYPE_BY_NAME_QUERY",
    "LIST_GROUP_WORK_ITEMS_QUERY",
    "LIST_PROJECT_WORK_ITEMS_QUERY",
    "UPDATE_WORK_ITEM_MUTATION",
]
