NORMAL_FILES = [
    "src/main.py",
    "src/utils/valid_url.py",
    "docs/README.md",
    "tests/test_file.py",
]

SENSITIVE_FILES = [
    ".git/config",
    ".git/info/exclude",
    ".gitlab/rules/chat.md",
    ".gitlab/duo/chat-rules.md",
    ".vscode/settings.json",
    ".idea/workspace.xml",
    ".metadata/config.xml",
]

SENSITIVE_DIRECTORIES = [
    ".git",
    ".vscode",
    ".idea",
    ".metadata",
]

SUSPICIOUS_PATHS = [
    ".env.development",
    ".env.local",
    ".env.production",
    ".env",
    ".git/",
    ".git/config",
    ".git/hooks/pre-commit",
    ".idea/",
    ".idea/misc.xml",
    ".idea/workspace.xml",
    ".metadata/",
    ".metadata/logs/log.txt",
    ".vscode/",
    ".vscode/launch.json",
    ".vscode/settings.json",
    "project/.env",
    "project/.git/config",
    "project/.idea/modules.xml",
    "project/.vscode/extensions.json",
    "src/.git/hooks/pre-push",
    "workspace/.metadata/plugins/",
    "../.env",
    "../../.git/config",
    "../../../.ssh/id_rsa",
    "../../../../etc/passwd",
    "src/../.env",
    "docs/../../.git/config",
    "tests/../../../.vscode/settings.json",
    "components/ui/../../.idea/workspace.xml",
    "..\\config",
    "..\\..\\.env",
    "src\\..\\.git/config",
    "docs/../\\.vscode/launch.json",
    "%2e%2e/config",
    "%2e%2e%2f%2e%2e/.env",
    "%2e%2e%2f%2e%2e%2f%2e%2e/.git/config",
    "%252e%252e/config",
    "%252e%252e%252f%252e%252e/.env",
    "../" * 50 + ".env",
    "../" * 100 + ".git/config",
    "../" * 200 + ".ssh/id_rsa",
    "../symlink_to_sensitive",
    "../../link_to_git",
    "../../../link_to_ssh",
    ".ENV",
    ".Git/CONFIG",
    ".VsCode/settingS.jsOn",
    ".sSh/CoNfIg",
    ".SSH/ID_RSA",
    "../ .env",
    "../../ .git/config",
    "../../../.ssh/ id_rsa",
    "../.env ",
    "../../.git/config ",
    "./../.env",
    "./../../.git/config",
    "./../../../.ssh/id_rsa",
    "./././../.env",
    "./.././../.git/config",
    "./../.././.ssh/id_rsa",
    "../.env/",
    "../../.git/config/",
    "../../../.ssh/",
    "../.env/",
    "../../.git/config/non-existent/../../",
    "../../.git/config/",
    "../../../.ssh/",
    "src/../.env",
    "src/./../../.git/config",
    "src/../utils/../.env",
    "./src/../.env",
    "src/utils/.env",
    "src/components/.git/config",
    "docs/api/v1/.vscode/settings.json",
    "src/utils/../../.env",
    "src/components/../../../.git/config",
    "docs/api/v1/../../../.vscode/settings.json",
    "src\\../.env",
    "src/../\\../.git/config",
    "src\\../utils\\../.env",
    "src/../src/../.env",
    "./src/../src/../.env",
    "src/./utils/.././../.env",
    "../etc/passwd",
    "../../etc/passwd",
    "../../../etc/passwd",
    "../../../../etc/passwd",
    "../../../../../../../etc/passwd",
    "./../etc/passwd",
    "./../../etc/passwd",
    "./../../../etc/passwd",
    "../.env",
    "../../.env.production",
    "../../../.git/config",
    "../../../../.ssh/id_rsa",
    "src/../.env",
    "docs/../../.git/config",
    "tests/../../../.ssh/known_hosts",
    "src/utils/../../../.env.local",
    "%2e%2e/etc/passwd",
    "%2e%2e%2f%2e%2e/etc/passwd",
    "..%2fconfig",
    "..\\etc\\passwd",
    "..\\..\\etc\\passwd",
    "src\\..\\..\\config",
    "../\\etc/passwd",
    "..\\/../config",
    "src/../\\../.env",
    "legitimate/path/../../../.git/hooks/pre-commit",
    "src/components/../../.vscode/settings.json",
    "docs/api/../../../.idea/workspace.xml",
    "../../../usr/bin/bash",
    "../../../../bin/sh",
    "../../../home/user/.bashrc",
    "../../root/.profile",
    "../etc/passwd\x00.txt",
    "../../config\x00.json",
    "../\u002e\u002e/etc/passwd",
    ".\u002f.\u002e/config",
]
