version: "experimental"
environment: remote
components:
  - name: "fix_pipeline_context"
    type: AgentComponent
    prompt_id: "fix_pipeline_context"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:goal"
        as: "merge_request_url"
    toolset: ["get_pipeline_errors", "list_merge_request_diffs", "read_file", "find_files", "list_dir"]
  - name: "fix_pipeline_create_plan"
    type: AgentComponent
    prompt_id: "fix_pipeline_create_plan"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:fix_pipeline_context.final_answer"
        as: "fix_pipeline_context_results"
    toolset: []
  - name: "fix_pipeline_execution"
    type: AgentComponent
    prompt_id: "fix_pipeline_execution"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:fix_pipeline_create_plan.final_answer"
        as: "fix_pipeline_plan"
    toolset:
      - create_file_with_contents
      - edit_file
      - find_files
      - mkdir
      - read_file
  - name: "fix_pipeline_git_add"
    type: DeterministicStepComponent
    inputs:
      - from: "context:project_http_url_to_repo"
        as: "repository_url"
      - from: "add"
        as: "command"
        literal: true
      - from: "-A"
        as: "args"
        literal: true
    tool_name: "run_git_command"
  - name: "fix_pipeline_git_commit"
    type: DeterministicStepComponent
    inputs:
      - from: "context:project_http_url_to_repo"
        as: "repository_url"
      - from: "commit"
        as: "command"
        literal: true
      - from: "-m 'fix failing pipeline'"
        as: "args"
        literal: true
    tool_name: "run_git_command"
  - name: "fix_pipeline_git_push"
    type: DeterministicStepComponent
    inputs:
      - from: "context:project_http_url_to_repo"
        as: "repository_url"
      - from: "push"
        as: "command"
        literal: true
      - from: "-o merge_request.create -o merge_request.title='Draft: fix failing pipeline'"
        as: "args"
        literal: true
    tool_name: "run_git_command"
routers:
  - from: "fix_pipeline_context"
    to: "fix_pipeline_create_plan"
  - from: "fix_pipeline_create_plan"
    to: "fix_pipeline_execution"
  - from: "fix_pipeline_execution"
    to: "fix_pipeline_git_add"
  - from: "fix_pipeline_git_add"
    to: "fix_pipeline_git_commit"
  - from: "fix_pipeline_git_commit"
    to: "fix_pipeline_git_push"
  - from: "fix_pipeline_git_push"
    to: "end"
flow:
  entry_point: "fix_pipeline_context"
