version: "experimental"
environment: remote
components:
  # Step 1: Gather context
  - name: "gather_context"
    type: AgentComponent
    prompt_id: "resolve_sast_vulnerability_context"
    prompt_version: "^1.0.0"
    inputs:
      - { from: "context:goal", as: "vulnerability_input" }
      - { from: "context:project_http_url_to_repo", as: "repository_url" }
    toolset: ["get_vulnerability_details", "read_file", "read_files", "grep", "find_files", "list_dir"]

  # Step 2: Create fix plan
  - name: "create_plan"
    type: AgentComponent
    prompt_id: "resolve_sast_vulnerability_create_plan"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:gather_context.final_answer"
        as: "vulnerability_context"
    toolset: ["read_file", "grep", "find_files"]

  # Step 3: Execute the fix
  - name: "execute_fix"
    type: AgentComponent
    prompt_id: "resolve_sast_vulnerability_execution"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:create_plan.final_answer"
        as: "resolution_plan"
    toolset: ["edit_file", "create_file_with_contents", "read_file", "run_command"]

  # Step 4: Validate the fix with tests
  - name: "validate_fix"
    type: AgentComponent
    prompt_id: "resolve_sast_vulnerability_test_validation"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:execute_fix.final_answer"
        as: "execution_results"
      - from: "context:create_plan.final_answer"
        as: "fix_plan"
    toolset: ["find_files", "run_tests", "grep", "read_files", "create_file_with_contents", "edit_file"]

  # Step 5: Stage, Commit, Push, and Open MR
  - name: "commit_and_open_mr"
    type: OneOffComponent
    prompt_id: "resolve_sast_vulnerability_commit_and_push"
    prompt_version: "^1.0.0"
    max_correction_attempts: 3
    inputs:
      - from: "context:gather_context.final_answer"
        as: "vulnerability_context"
      - from: "context:project_http_url_to_repo"
        as: "repository_url"
      - from: "context:workflow_id"
        as: "workflow_id"
    toolset: ["run_git_command"]

routers:
  - from: "gather_context"
    to: "create_plan"
  - from: "create_plan"
    to: "execute_fix"
  - from: "execute_fix"
    to: "validate_fix"
  - from: "validate_fix"
    to: "commit_and_open_mr"
  - from: "commit_and_open_mr"
    to: "end"

flow:
  entry_point: "gather_context"
