query($workflowId: AiDuoWorkflowsWorkflowID!) {
    duoWorkflowWorkflows(workflowId: $workflowId) {
        nodes {
            statusName
            projectId
            project {
                id
                name
                description
                httpUrlToRepo
                languages {
                    name
                    share
                }
                webUrl
                statisticsDetailsPaths {
                    repository
                }
                duoContextExclusionSettings {
                    exclusionRules
                }
                duoWorkflowStatusCheck {
                    foundationalFlowsEnabled
                    enabledFoundationalFlows
                }
                namespace {
                    aiSettings {
                        promptInjectionProtectionLevel
                    }
                }
            }
            namespaceId
            namespace {
                id
                name
                description
                webUrl
                aiSettings {
                    promptInjectionProtectionLevel
                }
            }
            agentPrivilegesNames
            preApprovedAgentPrivilegesNames
            mcpEnabled
            incrementalCheckpointsEnabled
            allowAgentToRequestUser
            webSearchEnabled
            latestCheckpoint {
                threadTs
                parentTs
                metadata
                compressedCheckpoint
                currentThread @gl_introduced(version: "19.4.0")
            }
            archived
            stalled
        }
    }
}
