mutation createAscpSecurityContext($input: AscpSecurityContextCreateInput!) {
  ascpSecurityContextCreate(input: $input) {
    securityContext {
      id
      summary
      authenticationModel
      authorizationModel
      dataSensitivity
      securityBoundary @gl_introduced(version: "19.5.0")
      scan {
        id
      }
      securityGuidelines {
        nodes {
          id
          name
          operation
          legitimateUse
          securityBoundary
          businessContext
          severityIfViolated
        }
      }
    }
    errors
  }
}
