X_GITLAB_REALM_HEADER = "x-gitlab-realm"
X_GITLAB_INSTANCE_ID_HEADER = "x-gitlab-instance-id"
X_GITLAB_GLOBAL_USER_ID_HEADER = "x-gitlab-global-user-id"
X_GITLAB_HOST_NAME = "x-gitlab-host-name"
X_GITLAB_NAMESPACE_ID = "x-gitlab-namespace-id"
X_GITLAB_PROJECT_ID = "x-gitlab-project-id"
X_GITLAB_FEATURE_ENABLED_BY_NAMESPACE_IDS = "x-gitlab-feature-enabled-by-namespace-ids"
