apiVersion: runway/v1
kind: RunwayKubernetesService
metadata:
  name: ai-gateway-gke
spec:
  services:
    app:
      image: "registry.gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/model-gateway:{{ .AppVersion }}"
      command: ["/home/aigateway/app/scripts/run.sh"]
      environment:
        AIGW_FASTAPI__API_PORT: "8080"
        HOME: "/root"
        AIGW_FASTAPI__METRICS_HOST: "0.0.0.0"
        AIGW_FASTAPI__METRICS_PORT: "8082"
        AIGW_GOOGLE_CLOUD_PROFILER__ENABLED: "true"
        AIGW_GOOGLE_CLOUD_PROFILER__VERBOSE: "2"
        AIGW_GOOGLE_CLOUD_PROFILER__PERIODS_MS: "10"
        AIGW_INSTRUMENTATOR__THREAD_MONITORING_ENABLED: "True"
        AIGW_INSTRUMENTATOR__THREAD_MONITORING_INTERVAL: "60"
        AIGW_CLOUD_CONNECTOR_SERVICE_NAME: "gitlab-ai-gateway"
        AIGW_AMAZON_Q__REGION: "us-east-1"
        AIGW_AMAZON_Q__ENDPOINT_URL: "https://us-east-1.prod.integration.qdev.ai.aws.dev"
      container_port: 5052
      protocol: http
      scalability:
        min_instances: 8
        max_instances: 100
        cpu_utilization: 70
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
          ephemeral-storage: "2Gi"
        limits:
          cpu: "2000m"
          memory: "8Gi"
          ephemeral-storage: "8Gi"
      startup_probe:
        path: "/monitoring/ready"
        initial_delay_seconds: 20
        # We have limited concurrency in staging, so picking a long period
        timeout_seconds: 10
        period_seconds: 17
        failure_threshold: 24
      liveness_probe:
        path: "/monitoring/healthz"
        timeout_seconds: 5
      load_balancing:
        external_load_balancer:
          enabled: true
        internal_load_balancer:
          enabled: false
