name: Mirror GitLab Main Branch

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote and fetch
        run: |
          git remote add gitlab https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist.git
          git fetch gitlab main

      - name: Backup .github directory
        run: |
          if [ -d ".github" ]; then
            mkdir -p /tmp/.github_backup
            cp -r .github/* /tmp/.github_backup/
          fi

      - name: Reset main branch to match GitLab
        run: |
          git checkout main
          git reset --hard gitlab/main

      - name: Restore .github directory
        run: |
          if [ -d "/tmp/.github_backup" ]; then
            mkdir -p .github
            cp -r /tmp/.github_backup/* .github/
            git add .github
            if git diff --staged --quiet; then
              echo "No changes to .github directory"
            else
              git commit -m "Restore .github directory after GitLab sync"
            fi
          fi

      - name: Push to GitHub
        run: |
          git remote set-url origin https://${{ secrets.GH_PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin main --push-option=bypass-secret-scanning
        env:
          GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
